name: Go Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - main

permissions:
  contents: read # Set minimal permissions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code with SHA-pinned action and avoid persisting credentials
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          persist-credentials: false # Prevents PRs from gaining access to the repository token
          ref: ${{ github.ref }} # Ensure the checkout uses the exact branch/commit that triggered the workflow

      - name: Set up Go
        uses: actions/setup-go@d60b41a563a30eac31c3ec623e6ff0b3f16e1a06
        with:
          go-version: 1.23.0

      - name: Download Required Dependencies
        run: go mod download

      - name: Generate Prisma Client
        run: go run github.com/steebchen/prisma-client-go generate

      - name: Build
        run: |
          echo "Building the application..."
          go build -v ./...

      - name: Test
        run: |
          echo "Running tests..."
          go test -v ./...
