name: Prisma Migrations

on:
  workflow_dispatch: # Allows manual triggering of migrations from the GitHub Actions UI
  push:
    branches:
      - main
    paths:
      - "prisma/**"  # Only trigger on changes to Prisma files or schema

permissions:
  contents: read  # Limit permissions to read-only by default

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: production  # Ensure this matches your GitHub environment setup with protection rules

    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # protects against any unintentional or malicious modifications
        with:
          persist-credentials: false # Prevent PRs from gaining access to the repository token
          ref: ${{ github.ref }} # Ensure checkout uses the exact branch or commit that triggered the workflow

      - name: Set up Go
        uses: actions/setup-go@d60b41a563a30eac31c3ec623e6ff0b3f16e1a06
        with:
          go-version: 1.23

      - name: Download Required Dependencies
        run: go mod download

      - name: Generate Prisma Client
        run: go run github.com/steebchen/prisma-client-go generate

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Store the DATABASE_URL in a local variable to avoid exposing it directly
          DB_URL="$DATABASE_URL"
          
          # Prevent potential injections by avoiding direct use of the environment variable
          if [ -z "$DB_URL" ]; then
            echo "DATABASE_URL is not set"
            exit 1
          fi
          echo "Starting Prisma migrations..."
          go run github.com/steebchen/prisma-client-go migrate deploy
